/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.softwarica.futsalmanagamentsystem.Components;

import com.softwarica.futsalmanagamentsystem.Dao.UserProvider;
import com.softwarica.futsalmanagamentsystem.Model.Futsal;
import com.softwarica.futsalmanagamentsystem.Utility.CallbackFunction;

/**
 *
 * @author Rishan
 */
public class FutsalComponent extends javax.swing.JPanel {
CallbackFunction onAddToFav,onBook, onEditTap, onDeleteTap;
    /**
     * Creates new form FutsalComponent
     */
    public FutsalComponent(Futsal futsal, CallbackFunction onAddToFav, CallbackFunction onBook, CallbackFunction onEditTap, CallbackFunction onDeleteTap) {
        initComponents();
        jLabel12.setText(futsal.courtTypeName);
        futsalNameLabel.setText(futsal.name);
        addressLabel.setText(futsal.location);
        priceLabel.setText(futsal.price + " /hr");
        openingTimeLabel.setText(futsal.openingHour + ":00-" + futsal.closingHour + ":00 ");
        this.onAddToFav=onAddToFav;
        this.onBook=onBook;
        this.onEditTap=onEditTap;
        this.onDeleteTap=onDeleteTap;
        if (UserProvider.getInstance().isAdmin()) {
            addToFavouriteButton.setVisible(!futsal.isFavourite);
//            bookFutsalButton.setVisible(false);
        } else {
            addToFavouriteButton.setVisible(!futsal.isFavourite);
            onEditButton.setVisible(false);
            onDeleteButotn .setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        futsalNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bookFutsalButton = new javax.swing.JButton();
        addToFavouriteButton = new javax.swing.JButton();
        jlabel1000 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        openingTimeLabel = new javax.swing.JLabel();
        onEditButton = new javax.swing.JButton();
        onDeleteButotn = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(197, 231, 189));

        futsalNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        futsalNameLabel.setText("Rishan Futsal");

        addressLabel.setText("Bhaktapur");

        jLabel12.setText("Side A-5");

        jLabel14.setText("Opening Time");

        bookFutsalButton.setBackground(new java.awt.Color(235, 196, 58));
        bookFutsalButton.setForeground(new java.awt.Color(255, 255, 255));
        bookFutsalButton.setText("Book");
        bookFutsalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFutsalButtonActionPerformed(evt);
            }
        });

        addToFavouriteButton.setBackground(new java.awt.Color(47, 207, 91));
        addToFavouriteButton.setForeground(new java.awt.Color(255, 255, 255));
        addToFavouriteButton.setText("Add to Favourite");
        addToFavouriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToFavouriteButtonActionPerformed(evt);
            }
        });

        jlabel1000.setText("Price");

        priceLabel.setText("1200/hrs");

        openingTimeLabel.setText("10:00 - 21:00");

        onEditButton.setText("Edit");
        onEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEditButtonActionPerformed(evt);
            }
        });

        onDeleteButotn.setText("Delete");
        onDeleteButotn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteButotnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(openingTimeLabel)
                                .addGap(39, 39, 39)
                                .addComponent(onEditButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onDeleteButotn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bookFutsalButton))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                        .addComponent(addToFavouriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel)
                            .addComponent(futsalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlabel1000, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(futsalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel)
                            .addComponent(jLabel12)
                            .addComponent(addToFavouriteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(bookFutsalButton)
                            .addComponent(jlabel1000))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(openingTimeLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onEditButton)
                            .addComponent(onDeleteButotn))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onDeleteButotnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteButotnActionPerformed
        // TODO add your handling code here:
        onDeleteTap.onTrigger();
    }//GEN-LAST:event_onDeleteButotnActionPerformed

    private void onEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEditButtonActionPerformed
        // TODO add your handling code here:
        onEditTap.onTrigger();
    }//GEN-LAST:event_onEditButtonActionPerformed

    private void addToFavouriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToFavouriteButtonActionPerformed
        // TODO add your handling code here:
        onAddToFav.onTrigger();
    }//GEN-LAST:event_addToFavouriteButtonActionPerformed

    private void bookFutsalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFutsalButtonActionPerformed
        // TODO add your handling code here:
        onBook.onTrigger();
    }//GEN-LAST:event_bookFutsalButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToFavouriteButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton bookFutsalButton;
    private javax.swing.JLabel futsalNameLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlabel1000;
    private javax.swing.JButton onDeleteButotn;
    private javax.swing.JButton onEditButton;
    private javax.swing.JLabel openingTimeLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
